#!/bin/bash

# prepare machine file for mcat "$TMPDIR/machines"
cat "$PE_HOSTFILE"
cat "$TMPDIR/machines"
uniq $TMPDIR/machines > $TMPDIR/u_machines

source /opt/intel/impi/5.1.3.223/bin64/mpivars.sh
export PATH=/shared/bin/singularity/bin:$PATH
export SINGULARITY_BINDPATH=/etc/rdma/dat.conf
     
mpirun -machinefile "$TMPDIR/u_machines" -np 2 -ppn 1 singularity exec ./rdma-latest.simg \ /opt/intel/impi/5.1.3.223/bin64/IMB-MPI1 PingPong


